### PR TITLE
AKS - Multi Cluster - get Azure Firewall Rules Groups to deploy without puking on concurrent PUT updates to the firewall

### PR DESCRIPTION
**Pull request by magrande**

### CODE REVIEW

**Review by ckittel — APPROVED** [review]
Sweet!

**Comment by magrande** [comment]
> Sweet!

I think this is ok, but I'm still testing it. That's why I converted it to draft

**Comment by magrande** [comment]
This is as much as we can do, since allLogs category is not supported yet.

\"BadRequest\",\r\n  \"message\": \"Category 'AllLogs' is not supported.\"\r\n}"}]}}

\"BadRequest\",\r\n  \"message\": \"Category 'allLogs' is not supported.\"\r\n}"}]}}

**Comment by ckittel** [comment]
It's `categoryGroup` for the logs.  Not `category` so that error message above is accurate and telling you that you're trying to set a `category` that doesn't exist, when you should be using `categoryGroup` -- can you instead update to use `categoryGroup` like the resource is expecting?

**Pull request merged**
