### PR TITLE
Introduce the AKS baseline's "saveenv.sh" feature

### PR DESCRIPTION
**Pull request by ckittel**
* Started adding the feature, only got the first couple of pages covered, got through the GitHub username and Azure AD pages.
* Also added one callout that we have in the AKS baseline around skipping a log in if needed

### CODE REVIEW

**Review by skabou — COMMENTED** [review]
I can't get the script to work.  Are there extra steps?
I am able to see my variable with 'set' but not with 'env'

`Requesting a Cloud Shell.Succeeded. 
Connecting terminal...

jason@Azure:~$ cd aks
jason@Azure:~/aks$ GITHUB_USER_NAME_AKS_MRB=$(echo $(gh auth status 2>&1) | sed "s#.*as \(.*\) (.*#\1#")
jason@Azure:~/aks$ echo $GITHUB_USER_NAME_AKS_MRB
skabou
jason@Azure:~/aks$ env | grep GITHUB_USER_NAME_AKS_MRB
jason@Azure:~/aks$ set | grep GITHUB_USER_NAME_AKS_MRB
GITHUB_USER_NAME_AKS_MRB=skabou
jason@Azure:~/aks$ ./saveenv.sh 
#!/bin/bash

jason@Azure:~/aks$ cat aks_baseline.env 
#!/bin/bash

jason@Azure:~/aks$ `

**Comment by ckittel** [comment]
Shoot, I missed a commit.  Thanks!  One moment please

**Comment by ckittel** [comment]
> I can't get the script to work. Are there extra steps? I am able to see my variable with 'set' but not with 'env' or 'export'
> 
> Requesting a Cloud Shell.Succeeded. Connecting terminal...
> 
> jason@Azure:~$ cd aks jason@Azure:~/aks$ GITHUB_USER_NAME_AKS_MRB=$(echo $(gh auth status 2>&1) | sed "s#._as (._) (.*#\1#") jason@Azure:~/aks$ echo $GITHUB_USER_NAME_AKS_MRB skabou jason@Azure:~/aks$ env | grep GITHUB_USER_NAME_AKS_MRB jason@Azure:~/aks$ set | grep GITHUB_USER_NAME_AKS_MRB GITHUB_USER_NAME_AKS_MRB=skabou jason@Azure:~/aks$ ./saveenv.sh #!/bin/bash
> 
> jason@Azure:~/aks$ cat aks_baseline.env #!/bin/bash
> 
> jason@Azure:~/aks$

Addressed in https://github.com/mspnp/aks-baseline-multi-region/pull/55/commits/e910c46df618d4f9bd708aebe9347abac25d8ceb  -- and also added the missing `.gitignore` changes.

**Review by skabou — APPROVED** [review]
Yay!  🚢

**Pull request merged**
